### ISSUE TITLE
Nach Ausführen der RestoreSymlinks.php bleiben .remove Dateien übrig

### ISSUE THREAD

**Issue by jscholtysik** [do-while/contao-BackupDB#10]
Nach der Ausführung der RestoreSymlinks.php werden zwar die Symlinks ordnungsgemäß wieder erstellt, die alten falschen Verlinkungen erhalten dann aber den Suffix .remove und werden nicht gelöscht. Kann man die RestoreSymlinks.php dahingehend erweitern, dass die .remove-Dateien nach der ordnungsgemäßen Erstellung der Symlinks automatisch gelöscht werden?

**Comment by do-while** [comment]
Hallo Joachim,
das habe ich absichtlich so gemacht, da ich helfen und nicht zerstören möchte. Wenn ich die Dateien nur umbenenne, sind sie weiterhin verfügbar. Alles was man löscht, ist weg.
Da ich letztlich nicht eindeutig beurteilen möchte, ob das wirklich weg kann, lasse ich lieber ein Backup stehen.

**Comment by jscholtysik** [comment]
Gibt es den die Möglichkeit, eine Option im Backend einzubauen, damit der Benutzer selbst entscheiden kann, ob er die Dateien gleich löschen möchte oder nicht?

**Comment by do-while** [comment]
Wenn ich als Extension-Entwickler das schon nicht mit Sicherheit weiß, möchte ich das nicht den Anwender fragen. Das gibt nur Rückfragen und letztlich entscheidet man ggf. genau falsch.

In der Historie war bereits die Entscheidung ob Backup oder Template so schwierig, dass sehr viele ein Template als Backup verwenden wollten, obwohl extra überall stand, dass es nicht funktioniert. Als mögliche Lösung, wenn man wirklich nichts anderes als ein Template mehr hat, habe ich in 4.4 eine weitere Datei erzeugt, die die im Template fehlende Struktur speichert. So kann man sich in der größten Not noch ein Backup zusammenbasteln.
