### ISSUE TITLE
Alternative E-Mail-Adresse für E-Mail-Benachrichtigung nach AutoBackup

### ISSUE THREAD

**Issue by operatorone** [do-while/contao-BackupDB#17]
Moin Moin,

wäre es denkbar im Backend eine Funktion hinzuzufügen, die es zulässt die E-Mail-Benachrichtigung nach AutoBackup auch an eine andere Adresse zu senden oder zusätzlich an eine weitere E-Mail-Adresse? Sprich, entweder bekommt nur der Admin die Mail, der Admin und der zusätzliche Empfänger oder nur der zusätzliche Empfänger. Meine Idee fußt darauf, dass oft der Seitenbetreiber als Admin eingetragen ist, aber der technische Betreuer z. B. Webmaster eine andere Adresse hat. Der Seitenbetreiber kann meist mit diesen technischen Benachrichtigungen nichts anfangen.

Viele Grüße
Tilman (operatorone)

**Comment by do-while** [comment]
Hallo Tilman,
genau dafür ist ja eigentlich die Unterscheidung mit E-Mail-Adresse des Systemadmins (in Einstellungen) und den Mailadressen der Seitenbetreibern (in den Startpunkten).
Hat man mehrere Startpunkte mit verschiedenen Betreibern, so ist es sowieso nicht gut die Datenbank per Mail zu verteilen, denn da sind immer alle Startpunkte enthalten.

**Comment by operatorone** [comment]
Hallo Hagen,

habe ich wieder was gelernt. Danke für den Tipp. Ich denke, damit lässt sich meine momentane Aufgabenstellung lösen. Ganz lieben Dank für die Rückmeldung.

Viele Grüße
Tilman
