### ISSUE TITLE
Individuelle Bezeichnung Autobackup-Dateien

### ISSUE THREAD

**Issue by operatorone** [do-while/contao-BackupDB#18]
Moin moin,

ich habe mich gefragt, ob es möglich wäre die Backup-Dateien die durch das Autobackup erzeugt werden, mit einer individuellen Bezeichnung auszustatten, z. B. "Kundenname_YYYYMMDD_HHMM.zip". Ich weiß natürlich nicht, ob das mit der Option "Anzahl der Backups bei AutoBackupDB" kollidiert, aber einen zusätzlichen Zähler an den individuellen Namen anzuhängen, fände ich völlig unproblematisch.

Viele Grüße
Tilman (operatorone)

**Comment by do-while** [comment]
Könnte man schon machen, hat auch mit der Anzahl kein Problem, aber wenn Du die Backups zentral sammeln willst (DSGVO ???), dann hast Du ja verschiedene Absender, von denen die Mails kommen, das sieht mir eher nach Mailfilterregeln aus.

**Comment by operatorone** [comment]
Hallo Hagen,

meine Absicht ist eher nicht die Backups zu sammeln, sondern eher besser zuordnen zu können, welches Backup woher kommt und zu wem gehört. In den Mails müsste ja nicht die Backup-Datei angehängt werden, sondern vielleicht nur der Dateiname hinterlegt sein, so hat man eine die Möglichkeit einer eindeutigen Zuordnung.

Viele Grüße
Tilman

**Comment by do-while** [comment]
Ein eindeutiger Name ist nicht möglich, da nach dem jetzigen Konzept die neueste Datei immer den Basisnamen hat, die älteren dann -1, -2 ... angehängt haben (beim AutoBackup). Bei der Erstellung eines Backups werden die alten Backup momentan immer um 1 hochgezählt.
Um das Löschen von alten AutoBackups zu erleichtern, habe ich damals diese Strategie gewählt.

**Comment by operatorone** [comment]
Ok. War nur so ne Idee.
