### ISSUE TITLE
Individueller Aufrufparameter mit Punkt geht nicht

### ISSUE THREAD

**Issue by zonky2** [do-while/contao-BackupDB#20]
wenn ich "Deinen" Parameter mit einem Punkt versehe wie `mEX.de3iD` kommt als Ausgabe nur `You cannot access this file directly!`

**Comment by do-while** [comment]
Wahrscheinlich gibst Du damit einen Dateityp .de3iD ab, der nicht ins Symfony umgeroutet wird.
Ich kann mir vorstellen, dass das an der .htaccess liegt.
