### ISSUE TITLE
FR: URL zum Aufrufen/Starten direkt in Backend

### ISSUE THREAD

**Issue by zonky2** [do-while/contao-BackupDB#21]
im BE unter `contao?do=BackupDB` den fertigen Link zum Anklicken rein setzen

**Comment by do-while** [comment]
Ist das eine Frage?
Du meinst, in der Textbeschreibung könnte man den Link hinschreiben?

**Comment by zonky2** [comment]
FR = feature request - also als Vorschlag/Bitte anzusehen...

ja, wäre prima, wenn im Text der Link da wäre a) zum Kopieren und b) zum Ausführen.

Um der Frage bei Multidomains vorzugreifen: ich würde die aktuell aufgerufene Domain verwenden, da diese - auch wenn es egal ist - sicher die "Administrations-Domain" sein wird, da man sich ja mit der ind BE eingeloggt hat.

**Comment by do-while** [comment]
Neue Version 1.4.2
