### ISSUE TITLE
Fehler bei Installation Contao 4.10 und 4.11

### ISSUE THREAD

**Issue by Homepage-Heldin** [do-while/contao-BackupDB#22]
Ich erhalte folgende Fehlermeldung bim Versuch das Packet über den Contao Manager zu installieren:

`composer update do-while/contao-backupdb-bundle contao/conflicts

1
> Resolving dependencies using Composer Cloud v3.0.1
2
!!! Current server is sponsored by: Contao Association !!!
3
4
5
[7.0MiB/0.24s] Loading composer repositories with package information
6
[54.3MiB/1.83s] Updating dependencies
7
[1093.8MiB/9.10s] Your requirements could not be resolved to an installable set of packages.
8
[1093.8MiB/9.11s] 
9
  Problem 1
10
    - contao/calendar-bundle is locked to version 4.11.0 and an update of this package was not requested.
11
    - Conclusion: don't install symfony/framework-bundle v5.2.3 (conflict analysis result)
12
    - Conclusion: don't install symfony/http-kernel v5.2.2 (conflict analysis result)
13
    - Conclusion: don't install symfony/http-kernel v5.2.3 (conflict analysis result)
14
    - Conclusion: don't install symfony/routing v5.2.3 (conflict analysis result)
15
    - contao/manager-bundle 4.11.0 requires symfony/web-profiler-bundle 4.4.* || 5.2.* -> satisfiable by symfony/web-profiler-bundle[v5.2.3].
16
    - contao/manager-bundle is locked to version 4.11.0 and an update of this package was not requested.
17
    - contao/manager-bundle 4.11.0 requires symfony/framework-bundle 4.4.* || 5.2.* -> satisfiable by symfony/framework-bundle[v4.4.0, ..., v4.4.19, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
18
    - symfony/framework-bundle[v4.4.0, ..., v4.4.19] require symfony/http-kernel ^4.4 -> satisfiable by symfony/http-kernel[v4.4.0, ..., v4.4.19].
19
    - You can only install one version of a package, so only one of these can be installed: symfony/http-kernel[v2.1.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.19, v5.0.0, ..., v5.2.3].
20
    - symfony/web-profiler-bundle v5.2.3 requires symfony/http-kernel ^5.2 -> satisfiable by symfony/http-kernel[v5.2.0, v5.2.1, v5.2.2, v5.2.3].
21
    - symfony/framework-bundle[v5.2.1, ..., v5.2.2] require symfony/http-kernel ^5.2.1 -> satisfiable by symfony/http-kernel[v5.2.1, v5.2.2, v5.2.3].
22
    - Conclusion: don't install symfony/http-kernel v5.2.1 (conflict analysis result)
23
    - Root composer.json requires do-while/contao-backupdb-bundle ^1.4 -> satisfiable by do-while/contao-backupdb-bundle[1.4.0, 1.4.1, 1.4.2].
24
    - Conclusion: don't install symfony/routing[v5.2.1] | install do-while/contao-backupdb-bundle[1.4.2] (conflict analysis result)
25
    - Conclusion: don't install symfony/routing[v5.2.0] | install do-while/contao-backupdb-bundle[1.4.2] (conflict analysis result)
26
    - Conclusion: don't install do-while/contao-backupdb-bundle[1.4.2] | install one of symfony/framework-bundle[v4.4.0, ..., v4.4.19] (conflict analysis result)
27
    - symfony/framework-bundle v5.2.0 requires symfony/routing ^5.2 -> satisfiable by symfony/routing[v5.2.0, v5.2.1, v5.2.2, v5.2.3].
28
    - Conclusion: don't install symfony/routing[v5.2.2] | install do-while/contao-backupdb-bundle[1.4.2] (conflict analysis result)
29
30
[1093.8MiB/9.11s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
31
[44.1MiB/10.04s] Memory usage: 44.08MB (peak: 1095.47MB), time: 10.04s.
32
[44.1MiB/10.04s] Finished Composer Cloud resolving.
33
34
35
`

**Comment by do-while** [comment]
Das Problem kann ich nachvollziehen. Es ist aber leider nicht damit getan Symfony 5 zuzulassen, denn im Routing hat sich einiges geändert. Da muss ich jetzt tiefer einsteigen und vielleicht einiges umschreiben.
Das kann noch ein paar Tage dauern.

**Comment by Homepage-Heldin** [comment]
Hallo Herr Klemp,

ich glaube, das Problem lag nicht am Plugin. Auf meinem Server waren Datenbanken beschädigt, was ich vorher nicht wußte.
Der Fehler konnte von meinem Hoster behoben werden und danach lief auch die Installation der Erweiterung durch :-)
Also ich glaube, das war ein Fehlalarm.

Trotzdem ganz vielen Dank für Ihre Nachricht.
—
Mit freundlichen Grüßen,
Christina Glatz
ch-web.design <https://ch-web.design/>

T: 0800 000 8171
T: 036421 70 90 12
M: ch@ch-web.design
www.ch-web.design
Impressum <https://ch-web.design/impressum> | Datenschutz <https://ch-web.design/datenschutz>













Pflichtinformationen gemäß Artikel 13 DSGVO Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. Details entnehmen Sie unserer Datenschutzerklärung <https://ch-web.design/datenschutz>

**Comment by Kahmoon** [comment]
Ih habe den gleichen Fehler. DB ist aber OK.

**Comment by fritzmg** [comment]
To avoid such problems, it is always best to add _all_ the dependencies that you use to your `composer.json` and not rely on anything that the `contao/core-bundle` requires. For example, the `symfony/framework-bundle` is missing in the dependencies, but used [here](https://github.com/do-while/contao-BackupDB/blob/e4d124c4b8378075ffb35ff83a15275806f933f1/src/Controller/BackupDbController.php#L14). The `symfony/config` package is missing in the dependencies, but used [here](https://github.com/do-while/contao-BackupDB/blob/e4d124c4b8378075ffb35ff83a15275806f933f1/src/ContaoManager/Plugin.php#L18). The `symfony/http-kernel` component is missing in the dependencies but used [here](https://github.com/do-while/contao-BackupDB/blob/e4d124c4b8378075ffb35ff83a15275806f933f1/src/ContaoManager/Plugin.php#L19) and [here](https://github.com/do-while/contao-BackupDB/blob/e4d124c4b8378075ffb35ff83a15275806f933f1/src/SoftleisterBackupDbBundle.php#L14).

**Comment by Anke** [comment]
Hallo, ich hatte bisher keine Probleme, aber jetzt in einer neuen 4.11.5-Installation:

```
$ /usr/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /kunden/147435_65462/webseiten/framework/web/contao-manager.phar.php composer require do-while/contao-backupdb-bundle --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

Using version ^1.4 for do-while/contao-backupdb-bundle
/kunden/147435_65462/webseiten/framework/composer.json has been updated

# Process terminated with exit code 0
# Result: OK


> Resolving dependencies using Composer Cloud v3.2.0
!!! Current server is sponsored by: Contao Association !!!


[6.6MiB/0.20s] Loading composer repositories with package information
[56.6MiB/1.97s] Updating dependencies
[1398.4MiB/15.78s] Your requirements could not be resolved to an installable set of packages.
[1398.4MiB/15.78s] 
  Problem 1
    - Root composer.json requires do-while/contao-backupdb-bundle ^1.4 -> satisfiable by do-while/contao-backupdb-bundle[1.4.0, 1.4.1, 1.4.2].
    - Conclusion: don't install symfony/http-kernel v5.2.2 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.3 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v4.4.21 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.4 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v4.4.22 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.5 (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle v4.4.24 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.6 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.7 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel[v5.2.8] | install one of symfony/framework-bundle[v4.4.25, v4.4.26, v5.2.0, ..., v5.2.11] (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel[v5.2.9] | install one of symfony/framework-bundle[v4.4.25, v4.4.26, v5.2.0, ..., v5.2.11] (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel[v5.2.10] | install one of symfony/framework-bundle[v4.4.26, v5.2.0, ..., v5.2.11] (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel[v5.2.11] | install one of symfony/framework-bundle[v5.2.0, ..., v5.2.11] (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle[v4.4.26] | install one of symfony/framework-bundle[v5.2.0, ..., v5.2.11] (conflict analysis result)
    - Conclusion: don't install symfony/framework-bundle[v4.4.25] | install one of symfony/framework-bundle[v5.2.0, ..., v5.2.11] (conflict analysis result)
    - symfony/framework-bundle[v5.2.0, ..., v5.2.11] require symfony/routing ^5.2 -> satisfiable by symfony/routing[v5.2.0, ..., v5.3.0].
    - Conclusion: don't install symfony/routing v5.2.0 (conflict analysis result)
    - Conclusion: don't install symfony/routing v5.2.1 (conflict analysis result)
    - Conclusion: don't install symfony/routing v5.2.2 (conflict analysis result)
    - Conclusion: don't install symfony/routing v5.2.3 (conflict analysis result)
    - Conclusion: don't install symfony/routing v5.2.4 (conflict analysis result)
    - Conclusion: don't install symfony/routing v5.2.6 (conflict analysis result)
    - Conclusion: don't install symfony/routing v5.2.7 (conflict analysis result)
    - Conclusion: don't install symfony/routing v5.2.9 (conflict analysis result)
    - Conclusion: don't install symfony/routing v5.2.10 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.0 (conflict analysis result)
    - Conclusion: don't install symfony/routing v5.3.0 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.1 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.2 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.3.3 (conflict analysis result)
    - contao/manager-bundle 4.11.5 requires symfony/web-profiler-bundle 4.4.* || 5.2.* -> satisfiable by symfony/web-profiler-bundle[v5.2.11].
    - contao/manager-bundle is locked to version 4.11.5 and an update of this package was not requested.
    - contao/manager-bundle 4.11.5 requires symfony/framework-bundle 4.4.* || 5.2.* -> satisfiable by symfony/framework-bundle[v4.4.0, ..., v4.4.26, v5.2.0, ..., v5.2.11].
    - symfony/framework-bundle[v4.4.0, ..., v4.4.20] require symfony/http-kernel ^4.4 -> satisfiable by symfony/http-kernel[v4.4.0, ..., v4.4.26].
    - You can only install one version of a package, so only one of these can be installed: symfony/http-kernel[v2.1.0, ..., v2.8.52, v3.0.0, ..., v3.4.49, v4.0.0, ..., v4.4.26, v5.0.0, ..., v5.3.3].
    - symfony/web-profiler-bundle v5.2.11 requires symfony/http-kernel ^5.2 -> satisfiable by symfony/http-kernel[v5.2.0, ..., v5.3.3].
    - Conclusion: don't install symfony/http-kernel v5.2.1 (conflict analysis result)

[1398.4MiB/15.78s] Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
[76.4MiB/16.99s] Memory usage: 76.44MB (peak: 1400.07MB), time: 17s.
[76.4MiB/16.99s] Finished Composer Cloud resolving.


# Cloud Job ID z30YEJZ3d4y5G2ylif4NKmeNRsAoVn4LU4Pq1eiMun3LDwVo15xpg3BTFitRQa6FQyUjbdXrtTRaEPF0REoWTfs5hEh7Y5VV77tTi9KFn7p failed
```
What can I do?
Gruß, Anke

**Comment by do-while** [comment]
Hallo Anke,
BackupDB ist noch nicht für Symfony 5 freigegeben, daher der Conflict.
Wenn Du "Alle Pakete aktualisieren" machst, dann wird Symfony auf Version 4 zurückgestuft und es läuft auch in Contao 4.11
Außerdem sollte man BackupDB noch nicht unter PHP 8 betreiben.

Updates werden kommen.

Gruß, Hagen

**Comment by Anke** [comment]
Merci vielmals, Hagen!

**Comment by do-while** [comment]
Jetzt ist die Version 1.5.0 veröffentlicht, jetzt sollte es kompatibel sein.
