### ISSUE TITLE
Abbruch der Installation unter Contao 4.12.4

### ISSUE THREAD

**Issue by CarstenWeithoener** [do-while/contao-BackupDB#24]
### Der Contao Manager gab während der Installation nachfolgende Fehlermeldung aus. 

composer require do-while/contao-backupdb-bundle
$ /opt/RZphp74/bin/php-cli -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=CET /mnt/web004/d0/66/539266/htdocs/xxxxx/web/contao-manager.phar.php composer require do-while/contao-backupdb-bundle --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction
Using version ^1.4 for do-while/contao-backupdb-bundle
/mnt/web004/d0/66/539266/htdocs/xxxxx/composer.json has been updated
\# Process terminated with exit code 0
\# Result: OK
composer update do-while/contao-backupdb-bundle contao/conflicts

\> Resolving dependencies using Composer Cloud v3.2.0
!!! Current server is sponsored by: Contao Association !!!
[6.8MiB/0.20s] Loading composer repositories with package information
[63.3MiB/1.84s] Updating dependencies
[1544.8MiB/12.06s] Your requirements could not be resolved to an installable set of packages.
[1544.8MiB/12.06s] 
  Problem 1
    - symfony/routing[v6.0.0, ..., v6.0.1] require php >=8.0.2 -> your php version (7.4.26.0) does not satisfy that requirement.
    - symfony/framework-bundle[v6.0.0, ..., v6.0.1] require php >=8.0.2 -> your php version (7.4.26.0) does not satisfy that requirement.
    - contao/manager-bundle is locked to version 4.12.4 and an update of this package was not requested.
    - contao/manager-bundle 4.12.4 requires symfony/web-profiler-bundle ^4.4 || ^5.2 -> satisfiable by symfony/web-profiler-bundle[v5.4.0].
    - Root composer.json requires do-while/contao-backupdb-bundle ^1.4 -> satisfiable by do-while/contao-backupdb-bundle[1.4.0, 1.4.1, 1.4.2].
    - symfony/web-profiler-bundle v5.4.0 requires symfony/framework-bundle ^5.3|^6.0 -> satisfiable by symfony/framework-bundle[v5.3.0, ..., v5.4.1, v6.0.0, v6.0.1].
    - symfony/framework-bundle[v5.4.0, ..., v5.4.1] require symfony/routing ^5.3|^6.0 -> satisfiable by symfony/routing[v5.3.0, ..., v5.4.0, v6.0.0, v6.0.1].
    - symfony/framework-bundle[v5.3.0, ..., v5.3.11] require symfony/routing ^5.3 -> satisfiable by symfony/routing[v5.3.0, ..., v5.4.0].
    - You can only install one version of a package, so only one of these can be installed: symfony/routing[v2.2.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.34, v5.0.0, ..., v5.4.0, v6.0.0, v6.0.1].
    - Conclusion: install symfony/routing v4.4.34 (conflict analysis result)
[1544.8MiB/12.06s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[77.4MiB/13.48s] Memory usage: 77.4MB (peak: 1547.91MB), time: 13.5s.
[77.4MiB/13.49s] Finished Composer Cloud resolving.
\# Cloud Job ID xxxxx failed

**Comment by do-while** [comment]
Du musst eine komplette Aktualisierung machen. Alle Abhängigkeiten müssen neu aufgelöst werden. BackupDB läuft momentan nicht zusammen mit Symfony 5, bei einer kompletten Aktualisierung wird daher Symfony auf die Version 4 zurückgestuft.

Eine neue Version ist in der dev-master enthalten, dort fehlt aber die Route für das automatische Backup per Cron, daher ist die Version noch nicht allgemein freigegeben. Wenn Du das Cron-Backup nicht nutzt, kannst Du es mit dem dev-master probieren (sollte funktionieren).

**Comment by CarstenWeithoener** [comment]
Danke für die schnelle Hilfe!
