### ISSUE TITLE
Nicht PHP 8 tauglich?

### ISSUE THREAD

**Issue by spacefront** [do-while/contao-BackupDB#27]
Kann es sein, dass die Erweiterung nicht PHP 8 tauglich ist - ich bekomme jedes mal eine Fehlermeldung

**Comment by do-while** [comment]
Hallo,
Die Stable-Version von BackupDB läuft momentan nicht zusammen mit Symfony 5 und nicht mit PHP 8,

Eine neue Version ist in der dev-master enthalten, dort fehlt aber die Route für das automatische Backup per Cron, daher ist die Version noch nicht allgemein freigegeben. Wenn Du das Cron-Backup nicht nutzt, kannst Du es mit dem dev-master probieren (sollte dann funktionieren).

**Comment by spacefront** [comment]
Ah Danke für die Info - dann nehme ich erstmal die dv-master ich teste es bei der nächsten Installation
