### ISSUE TITLE
Contao 4.13 compatibility

### ISSUE THREAD

**Issue by Kahmoon** [do-while/contao-BackupDB#28]
Hi,

when i try to update my system from 4.12.6 to 4.13 i get an error

PHP 7.4

```
[7.4MiB/0.24s] Loading composer repositories with package information
[36.8MiB/12.12s] Updating dependencies
[106.2MiB/12.78s] Your requirements could not be resolved to an installable set of packages.
[106.2MiB/12.79s] 
  Problem 1
    - Root composer.json requires contao/manager-bundle 4.13.* -> satisfiable by contao/manager-bundle[4.13.0].
    - do-while/contao-backupdb-bundle[1.4.0, ..., 1.4.2] require symfony/routing ^3.0 || ^4.0 -> satisfiable by symfony/routing[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37].
    - You can only install one version of a package, so only one of these can be installed: symfony/routing[v2.2.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3, v6.0.0, v6.0.1, v6.0.3].
    - contao/manager-bundle 4.13.0 requires symfony/routing ^5.4 -> satisfiable by symfony/routing[v5.4.0, v5.4.3].
    - Root composer.json requires do-while/contao-backupdb-bundle ^1.4 -> satisfiable by do-while/contao-backupdb-bundle[1.4.0, 1.4.1, 1.4.2].
```

But i can see that there is a backupdb version 1.5. Its not suggested by contao manager. 

<img width="425" alt="Bildschirmfoto 2022-02-18 um 09 37 38" src="https://user-images.githubusercontent.com/6390770/154647569-63956cb9-1dcc-4630-9394-f084fec5eaf2.png">

Also setting my compser.json manually to ^1.5 it dows not work!?
<img width="270" alt="Bildschirmfoto 2022-02-18 um 09 29 52" src="https://user-images.githubusercontent.com/6390770/154646382-7c202308-227a-4acd-aa63-2be30051c543.png">

VG Frank

**Comment by berecont** [comment]
i can confirm

**Comment by fritzmg** [comment]
> But i can see that there is a backupdb version 1.5. Its not suggested by contao manager.
>
> Also setting my compser.json manually to ^1.5 it dows not work!?

As already explained on the forum: there is no version `1.5.0`. The README mentions it, but it was never tagged (or the tag got deleted at some point).

**Comment by mibrume** [comment]
Currently I run in an error upgrading or installing this extension in Contao 4.13.0.

Is there a compatibility fix planned? Would like it.

The issue is right, even when the version is wrong.

**Comment by fritzmg** [comment]
See https://community.contao.org/de/showthread.php?82529-BackupDB-Version-1-4-2-funktioniert-nicht-in-Contao-4-13

**Comment by do-while** [comment]
Jetzt ist die Version 1.5.0 veröffentlicht, jetzt sollte es kompatibel sein.
