### ISSUE TITLE
count() mit null als Argument

### ISSUE THREAD

**Issue by fiedsch** [do-while/contao-BackupDB#31]
Zu https://community.contao.org/de/showthread.php?82805-BackupDB-Version-1-5-1-funktioniert-nicht-in-Contao-4-13-1

Die Zeile
https://github.com/do-while/contao-BackupDB/blob/5e0c1df9d42726e89ee9333fcfa360f33c2d241e/src/Resources/contao/classes/BackupDbCommon.php#L221 muss wahrscheinlich
```
  $result .= "CREATE TABLE `" . $table . "` (\n  " . implode(",\n  ", $tablespec['TABLE_FIELDS']) . (count($tablespec['TABLE_CREATE_DEFINITIONS'] ?? []) ? ',' : '') . "\n";
```
lauten, damit es kein Problem gibt, wenn `$tablespec['TABLE_CREATE_DEFINITIONS']` nicht gesetzt ist.

**Comment by do-while** [comment]
Im Warmup werden einige Konstanten oder Texte nicht geladen.
Danke für Hinweis und Lösung!
