### ISSUE TITLE
Vorschlag zur Optimierung der DB-Backups

### ISSUE THREAD

**Issue by tschero** [do-while/contao-BackupDB#32]
Hallo Zusammen,

beim Import der mit backup-db-bundle erstellten Datenbankbackups, laufe ich bei mehreren Hostern öfter in einen Timeout. Ich verwendet für Contao in der Regel externe Themes mit sehr viel DB-Inhalt.

Wäre es eine Option, die Backups etwas zu optimieren? Den Hinweis habe ich von Leo Feyer im Zuge von Fehlersuche mit einem M3 Server von Hostingwerk bekommen. Die beiden betroffenen Klassen des Bundles habe ich entsprechend angepasst und ausgiebig getestet. Der Import geht deutlich schneller vonstatten und bei keinem von mir verwendeten Hoster kommt mehr der Timeout.

Hier der Vorschlag:
SET autocommit = 0;
----------- Hier der Dateiinhalt von BackupDB
SET autocommit = 1;

Entsprechende Pullrequests sind erstellt

VG
tschero

**Comment by do-while** [comment]
This was implemented in 1.6.0
