### ISSUE TITLE
Contao 5.x?

### ISSUE THREAD

**Issue by m-werk** [do-while/contao-BackupDB#38]
Hallo,

eine Frage: Wird es dieses Modul auch für Contao 5.x geben? Und wenn ja, kann man schon einen Zeitpunkt sagen, wann es soweit sein wird?

LG, Andi

**Comment by do-while** [comment]
Ich habe mir vorgenommen zur ersten 5er LTS-Version (5.3) meine Erweiterungen dafür anzubieten. Sicherlich haben die kommerziellen Erweiterungen Priorität, BackupDB ist mir aber auch sehr wichtig.

**Comment by m-werk** [comment]
Danke für die Information.
