### ISSUE TITLE
MySQL-Dump can't be imported because of  '\' Default-Value

### ISSUE THREAD

**Issue by tabcontao** [do-while/contao-BackupDB#39]
When I export my database in Contao 5.3.11 with installed terminal42/contao-leads, the MySQL-Dump cannot be imported in phpMyAdmin. A problem occurs when creating table 'tl_lead_export'. The column 'csvEscape' has Default-Value of '\'. In my MySQL-Dump the create table statement looks like this:
`#---------------------------------------------------------
# Table structure for table 'tl_lead_export'
#---------------------------------------------------------
CREATE TABLE `tl_lead_export` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `pid` int(10) unsigned NOT NULL default '0',
  `tstamp` int(10) unsigned NOT NULL default '0',
  `name` varchar(255) NOT NULL default '',
  `type` varchar(32) NOT NULL default '',
  `filename` varchar(128) NOT NULL default '',
  `headerFields` char(1) NOT NULL default '',
  `export` varchar(8) NOT NULL default 'all',
  `output` varchar(8) NOT NULL default 'both',
  `fields` mediumblob NULL,
  `tokenFields` mediumblob NULL,
  `csvSeparator` varchar(4) NOT NULL default ',',
  `csvEnclosure` varchar(4) NOT NULL default '"',
  `csvEscape` varchar(4) NOT NULL default '\',
  `eol` varchar(2) NOT NULL default '',
  `useTemplate` char(1) NOT NULL default '',
  `startIndex` int(10) unsigned NOT NULL default '0',
  `sheetIndex` int(10) unsigned NOT NULL default '0',
  `expression` text NULL,
  `lastRun` int(11) NULL,
  `skipLastRun` char(1) NOT NULL default '',
  `template` binary(16) NULL,
  PRIMARY KEY  (`id`),
  KEY `pid` (`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC AUTO_INCREMENT=1;
`
Comparing with a MySQL-Dump created with phpMyAdmin, which I can import successfully, this one differs at column csvEscape. It notes the default value as '\\'. Probably the '\' needs to be escaped as '\\'.

**Comment by tabcontao** [comment]
The end above should read:

Probably the '\\' needs to be escaped as '\\\\'.

**Comment by tabcontao** [comment]
Hmm, totally messed up with the '\\' sign also in the create table statement above. BackupDB has it as a single backslash ('\\'), phpMyAdmin as an escaped backslash ('\\\\')

**Comment by do-while** [comment]
Das sollte jetzt in der Version 2.0.1 behoben sein.
This should now be fixed in version 2.0.1
